# Generated by Django 5.1.1 on 2024-10-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.SmallIntegerField(choices=[(-1, 'Private'), (0, 'Female'), (1, 'Male')], default=-1)),
                ('birthday', models.DateField(null=True)),
                ('avatar_url', models.CharField(max_length=1500, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(choices=[('ACTIVATED', 'Activated'), ('UNVERIFIED', 'Unverified'), ('BLOCKED', 'Blocked')], max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin')], max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
